# Generated by Django 6.1 on 2026-09-14 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('salaires', 'Salaires'), ('fournitures_medicales', 'Fournitures médicales'), ('equipement', 'Équipement'), ('electricite_eau', 'Électricité / Eau'), ('maintenance', 'Maintenance / Réparations'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('montant', models.PositiveIntegerField(help_text='Montant en francs guinéens (GNF).')),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True, help_text="Une dépense retirée n'apparaît plus dans les calculs.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depense', '-id'],
            },
        ),
    ]
