# Generated by Django 6.1 on 2026-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='actif',
            field=models.BooleanField(default=True, help_text="Un dossier archivé n'apparaît plus dans les listes."),
        ),
    ]
