# Generated by Django 6.1 on 2026-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnostic',
            field=models.TextField(blank=True, help_text='Diagnostic posé par le praticien.'),
        ),
    ]
