# Generated by Django 6.1 on 2026-09-07 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actes', '0001_initial'),
        ('patients', '0003_patient_diagnostic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('impayee', 'Impayée'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='impayee', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_emission', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_acte', models.CharField(max_length=150)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_facture', to='actes.actemedical')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Numéro de transaction, si applicable.', max_length=100)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture')),
            ],
            options={
                'ordering': ['-date_paiement', '-id'],
            },
        ),
    ]
