# Generated by Django 6.1 on 2026-09-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='motif_remise',
            field=models.CharField(blank=True, help_text='Raison de la remise, pour la traçabilité.', max_length=255),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise_globale_pourcentage',
            field=models.PositiveIntegerField(default=0, help_text='Remise en pourcentage appliquée sur le total de la facture (0 à 100).'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='remise_pourcentage',
            field=models.PositiveIntegerField(default=0, help_text='Remise en pourcentage sur cette ligne (0 à 100).'),
        ),
    ]
