# Generated by Django 6.1 on 2026-09-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_diagnostic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('termine', 'Terminé'), ('absent', 'Patient absent'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='patients.patient')),
                ('praticien', models.ForeignKey(limit_choices_to={'role__in': ['medecin_chef', 'medecin']}, on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
