# Generated by Django 6.1 on 2026-09-08 14:54

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_diagnostic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('type_cliche', models.CharField(choices=[('retro_alveolaire', 'Rétro-alvéolaire'), ('panoramique', 'Panoramique'), ('bite_wing', 'Bite-wing'), ('cbct_3d', 'CBCT / 3D'), ('autre', 'Autre')], default='retro_alveolaire', max_length=20)),
                ('date_cliche', models.DateField(blank=True, default=None, null=True)),
                ('dent_concernee', models.CharField(blank=True, help_text='Ex. 26, 36-37, arcade complète...', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True, help_text="Un cliché retiré n'apparaît plus dans les listes actives.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radiographies', to='patients.patient')),
                ('praticien', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['medecin_chef', 'medecin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiographies_prises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_cliche', '-date_creation'],
            },
        ),
    ]
