# Generated by Django 6.1 on 2026-09-14 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actes', '0001_initial'),
        ('patients', '0003_patient_diagnostic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plan', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_creation_plan', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20)),
                ('diagnostic', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_traitement', to='patients.patient')),
                ('praticien', models.ForeignKey(limit_choices_to={'role__in': ['medecin_chef', 'medecin']}, on_delete=django.db.models.deletion.PROTECT, related_name='plans_traitement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation_plan', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LignePlanTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_acte', models.CharField(blank=True, max_length=150)),
                ('dent_concernee', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('realise', models.BooleanField(default=False)),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_plan_traitement', to='actes.actemedical')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='plans_traitement.plantraitement')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
