# Generated by Django 6.1 on 2026-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('consultation', 'Consultation'), ('soin_conservateur', 'Soin conservateur (détartrage, carie...)'), ('endodontie', 'Endodontie (dévitalisation)'), ('chirurgie', 'Chirurgie / extraction'), ('prothese', 'Prothèse dentaire'), ('orthodontie', 'Orthodontie'), ('radiographie', 'Radiographie / imagerie'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('tarif', models.PositiveIntegerField(help_text='Tarif en francs guinéens (GNF).')),
                ('duree_estimee_minutes', models.PositiveIntegerField(default=30)),
                ('actif', models.BooleanField(default=True, help_text="Un acte désactivé n'apparaît plus dans les nouvelles sélections.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
